### ISSUE TITLE
Error: Can't create Virtual Machine.:password: should include uppercase and lowercase characters

### ISSUE THREAD

**Issue by drwmrrs** [virtuozzo/OnApp-WHMCS-Module#1]
Hi Guys,

I've just tried to module create a VM through the WHMCS admin interface and I'm receiving the following error:

`Module Create Failed - Service ID: 53 - Error: Can't create Virtual Machine.:password: should include uppercase and lowercase characters`

I've tried multiple password combinations and even lowered the max password length in OnApp.

Is this an issue with the module not passing the password field value to OnApp 3.0?

I'm using all the correct branches (user module, wrapper and WHMCS module) from the 3.0 branch.

There are no API / PHP errors in the module logs.

**Comment by drwmrrs** [comment]
Any update on this?

**Comment by yatskovets** [comment]
Hello,

Could you please send me PHP code example on ayats@onapop.com?

Thanks.
