### ISSUE TITLE
Promotions are not applied to invoices

### ISSUE THREAD

**Issue by istzp** [virtuozzo/OnApp-WHMCS-Module#4]
Hello,
maybe it's not an issue, it's more like feature request:
as I see whmcs promotions are not applied to invoices generated with this module.
Is it possible to fix this? Or maybe it's planned for next release?

**Comment by ghost** [comment]
Please, provide more details.

**Comment by ghost** [comment]
Oh sorry. This module is not in development anymore.

**Comment by istzp** [comment]
Yes, sorry, I've mixed up modules. Thanks.
